baseURL = 'https://vegetacodes.github.io/'
languageCode = 'en-us'
theme = 'hyde'
title = 'Uday K'

DefaultContentLanguage = "en"
Paginate = 10
SectionPagesMenu = "main"
enableRobotsTXT = true
googleAnalytics = "G-DLYZJ9VDDD"

[services.disqus]
shortname = "uday-1"

[Menus]
main = [
  {Name = "<img src='/icons/github.svg' width='24' alt='GitHub'/>", URL = "https://github.com/udaykadaboina"},
  {Name = "<img src='/icons/linkedin.svg' width='24' alt='LinkedIn'/>", URL = "https://www.linkedin.com/in/udaybhaskark/"},
  {Name = "<img src='/icons/stackoverflow.svg' width='24' alt='StackOverflow'/>", URL = "https://stackoverflow.com/users/981616/uday"},
  {Name = "About", URL = "/about"},
  {Name = "Tags", URL = "/tags"},
]

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
author = ""
copyright = "Made with ❤️ in Boston using <a href='https://gohugo.io/'>Hugo</a> & <a href='https://github.com/spf13/hyde'>Hyde</a> theme."
description = "Software Engineer, ML, Rowing"
favicon = ""
site_logo = ""
text_color = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
