baseURL = 'https://vegetacodes.github.io/'
languageCode = 'en-us'
title = 'Uday K'
theme = 'hyde'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "G-DLYZJ9VDDD"
enableRobotsTXT = true

disqusShortname = "uday-1"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/udaykadaboina"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/udaybhaskark/"},
      {Name = "StackOverflow", URL = "https://stackoverflow.com/users/981616/uday"},
      {Name = "About", URL = "/about"}
  ]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Software Engineer, ML, Rowing"
  copyright = "Made with ❤️ in Boston using Hugo & Hyde theme."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
